fix(LiteFlowService): NullPointerException
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiClass.getSuperClassType()" because "psiClass" is null
	at top.xystudio.plugin.idea.liteflowx.service.LiteFlowService.isLiteFlowSlot(LiteFlowService.java:171